### ISSUE TITLE
Link in "READ ME" not working

### ISSUE THREAD

**Issue by HideousWizard** [RAKWireless/WisBlock#24]
The link for the source code in this is not working this link: https://github.com/RAKWireless/WisBlock/tree/master/examples/communications/LoRa/LoRaWAN/LoRaWAN_OTAA/

**Comment by beegee-tokyo** [comment]
Fixed. Thank you for reporting.

**Comment by HideousWizard** [comment]
It still comes up with error 404.

**Comment by beegee-tokyo** [comment]
The new link is https://github.com/RAKWireless/WisBlock/blob/master/examples/RAK4630/communications/LoRa/LoRaWAN and it works.
