### ISSUE TITLE
Missing files for RAK18000_Stereo

### ISSUE THREAD

**Issue by EdBallou** [RAKWireless/WisBlock#26]
###Summary

Under **Load Examples** on:
https://github.com/RAKWireless/WisBlock/tree/master/quickstart/RAK4630

There is a reference to RAK18000_Stereo. Clicking on this link produces a 404 or otherwise missing files.

You can see there is no RAK18000_Stereo folder at:
https://github.com/RAKWireless/WisBlock/tree/master/examples/RAK4630/IO

### Defining Done

* [ ] Add missing files

**Comment by beegee-tokyo** [comment]
Fixed with commit [#cc0c5f](https://github.com/RAKWireless/WisBlock/commit/cc0c5f0f5aba558851441d4f59c44c6244c33a00)

**Comment by beegee-tokyo** [comment]
Thank you for reporting the problem.
