### ISSUE TITLE
What is the licence requirement for this code?

### ISSUE THREAD

**Issue by Cloolalang** [RAKWireless/WisBlock#3]
Hey Rak, This looks like a good API for use developers.
Is the code copyright? How can we use/sell devices with this code?
If we need a license please can you tell us how to get that?
Best Wishes

**Comment by beegee-tokyo** [comment]
Hi @Cloolalang 
The example source codes provided by RAK are open source and are not under copyright. You are free to use the whole or part of the example codes in your commercial products sold to customers. There is no license required for the RAK provided example codes.

**But we are using 3rd party libraries in our example code. You have to check the copyright/license requirements for these libraries by yourself**
