### ISSUE TITLE
Broken link in bootloader/RAK4630 README, link to 4630 bootloader hex file 

### ISSUE THREAD

**Issue by leroyle** [RAKWireless/WisBlock#32]
Within the README at https://github.com/RAKWireless/WisBlock/tree/master/bootloader/RAK4630
 the link to the bootloader is broken. Looks like it was not changed when the files were moved
It's the "here" link.
"Download the booloader from here"

**Comment by beegee-tokyo** [comment]
Thanks for reporting.
Fixed with commit https://github.com/RAKWireless/WisBlock/commit/1f52672a815ef13df16ddca9bcd1bb1dcacfc0e9
