### ISSUE TITLE
link to bootloader is invalid

### ISSUE THREAD

**Issue by mkinney** [RAKWireless/WisBlock#36]
On this page: https://github.com/RAKWireless/WisBlock/tree/master/bootloader/RAK4630

The link to download the bootloader is:
https://github.com/RAKWireless/WisBlock/blob/master/bootloader/RAK4630/new

But that link is a 404

**Comment by beegee-tokyo** [comment]
Thanks for reporting this. I will correct it next year.

Here is the link to the latest RAK4630/RAK4631 bootloader: https://github.com/RAKWireless/WisBlock/tree/master/bootloader/RAK4630/V0.4.2

**Comment by beegee-tokyo** [comment]
Fixed with https://github.com/RAKWireless/WisBlock/commit/58ed5e530658a4be522dffad0bb960a781cee7ec

Updated bootloader flash manuals as well.
