### ISSUE TITLE
Examples for RAK 11300 don't work

### ISSUE THREAD

**Issue by fabltd** [RAKWireless/WisBlock#38]
There are errors with the RAK 11300 docs:

(https://github.com/RAKWireless/WisBlock/tree/master/examples/RAK11300/communications/LoRa/LoRaWAN)

Does not referene the RAK 11300

The example does not work in Platform IO - Errors with printf.

**Comment by fabltd** [comment]
On this Page:

(https://docs.rakwireless.com/Product-Categories/WisBlock/RAK11310/Overview/)

Links to Install Ardunio or Platform IO cores are for the wrong device.

**Comment by beegee-tokyo** [comment]
It does, here is the initialization for the RAK11300, which is the stamp module on the RAK11310:

https://github.com/RAKWireless/WisBlock/blob/ec390aae2534dd79d671b7c8af77409299b90435/examples/RAK11300/communications/LoRa/LoRaWAN/LoRaWAN_OTAA_ABP/LoRaWAN_OTAA_ABP.ino#L82

**Comment by beegee-tokyo** [comment]
> There are errors with the RAK 11300 docs:
> 
> (https://github.com/RAKWireless/WisBlock/tree/master/examples/RAK11300/communications/LoRa/LoRaWAN)
> 
> Does not referene the RAK 11300
> 
> The example does not work in Platform IO - Errors with printf.

It does, here is the initialization for the RAK11300, which is the stamp module on the RAK11310:

https://github.com/RAKWireless/WisBlock/blob/ec390aae2534dd79d671b7c8af77409299b90435/examples/RAK11300/communications/LoRa/LoRaWAN/LoRaWAN_OTAA_ABP/LoRaWAN_OTAA_ABP.ino#L82

**Comment by beegee-tokyo** [comment]
> On this Page:
> 
> (https://docs.rakwireless.com/Product-Categories/WisBlock/RAK11310/Overview/)
> 
> Links to Install Ardunio or Platform IO cores are for the wrong device.

Thanks for pointing to this flaw.
Please use this guide:
https://github.com/RAKWireless/RAKwireless-Arduino-BSP-Index
