### ISSUE TITLE
use releases for bootloaders?

### ISSUE THREAD

**Issue by mkinney** [RAKWireless/WisBlock#43]
Looking at the download https://github.com/RAKWireless/WisBlock/blob/master/bootloader/RAK4630/Latest/WisCore_RAK4631_Board_Bootloader.zip

from the https://github.com/RAKWireless/WisBlock/tree/master/bootloader/RAK4630 page.

Perhaps that zip file should be pushed to a release?

If the CI cannot build them (due to some internal reason, you can always create a release manually and push the files into it). If you do have the steps, but need help adding them to your CI, share the steps, and I'll see if I can help adding it.

I'm planning on consuming that Bootloader in the meshtastic-flasher tool ( see https://github.com/meshtastic/Meshtastic-gui-installer ) and I'd prefer having a stable endpoint with version. In other words, I'd like to know that bootloader release 1.2.3 has a date of xxx  and SoftDevice version yyy when I query the INFO_UF2.TXT file.

**Comment by beegee-tokyo** [comment]
Hi @mkinney 
The bootloader is not compiled here in Github. It is compiled somewhere in China on a local machine. We have the sources here only for reference.
But I can create releases here manually for the latest version.

**Comment by mkinney** [comment]
Sources would be great, but not necessary.

That'd be awesome if they were added to a "manual" release. Thank you!

**Comment by mkinney** [comment]
Also, please let me know when you get rid of the existing link for that zip as I'll need to change it, too. :-)

**Comment by beegee-tokyo** [comment]
Pushed a manual release, please check.

Not sure what you mean with
> Also, please let me know when you get rid of the existing link for that zip as I'll need to change it, too. :-)

**Comment by mkinney** [comment]
Wow. That was fast. Ignore my last question about the existing link. I'll change to the release file.

Can you add one more thing?

Can you add the info to the release note? (or at least the "Date"):

```
UF2 Bootloader 0.4.2 lib/nrfx (v2.0.0) lib/tinyusb (0.10.1-293-gaf8e5a90) lib/uf2 (remotes/origin/configupdate-9-gadbb8c7)
Model: WisBlock RAK4631 Board
Board-ID: WisBlock-RAK4631-Board
Date: Dec  1 2021
SoftDevice: S140 6.1.1
```

and the INFO_UF2.TXT file, too?

[INFO_UF2.TXT](https://github.com/RAKWireless/WisBlock/files/7984577/INFO_UF2.TXT)

**Comment by mkinney** [comment]
Otherwise, that release https://github.com/RAKWireless/WisBlock/releases/tag/0.4.2 looks great!

**Comment by beegee-tokyo** [comment]
Ok, I will close this then.

Anyway we try to _**NOT**_ update the bootloader too often. Only if there is a bug.
