### ISSUE TITLE
Link to .h file not valid

### ISSUE THREAD

**Issue by EdBallou** [RAKWireless/WisBlock#47]
Looking at https://github.com/RAKWireless/WisBlock/tree/master/examples/common/sensors/RAK1901_Temperature_Humidity_SHTC3

A line of code references SparkFun_SHTC3.h here:
#include "SparkFun_SHTC3.h" // Click here to get the library: http://librarymanager/All#SparkFun_SHTC3

The "librarymanager" link is not valid.

Do you mean to link here? https://github.com/sparkfun/SparkFun_SHTC3_Arduino_Library/blob/master/src/SparkFun_SHTC3.h

**Comment by beegee-tokyo** [comment]
What are you using? Arduino IDE < V2 or the new Arduino IDE >= V2 or PlatformIO?

The link is valid if you are in Arduino < V2

Right click on it, the library manager is opening and shows you the library to install.

If it doesn't, than there is something wrong with your Arduino IDE.

![image](https://user-images.githubusercontent.com/512690/154875662-ee73ff12-f1d5-4ca6-8c97-6072754c52c3.png)
