### ISSUE TITLE
Rak11300 - Error while uploading the sketch

### ISSUE THREAD

**Issue by Famosi** [RAKWireless/WisBlock#50]
**[Linux]**

I'm having the error "An error occurred while uploading the sketch" every time I try to upload a sketch to my Rak11300.
I have "show verbose output during: compilation and upload" but no further info are displayed.

This happens with all the examples and even using an empty "new project".

I've followed this guide https://docs.rakwireless.com/Knowledge-Hub/Learn/Installation-of-Board-Support-Package-in-Arduino-IDE/ and also tried to update the firmware as suggested there.

Any suggestion? What can I do? 

I'm using Arduino IDE but also tried using Platform IO.

**[Windows]**
Fixed the issue by manually run `post_install.bat`

**Comment by beegee-tokyo** [comment]
Did you try to run the [post_install.sh](https://github.com/RAKWireless/RAK-RP-Arduino/blob/main/post_install.sh) on Linux?

**Comment by Famosi** [comment]
That fixed my issue... thanks :)

**Comment by beegee-tokyo** [comment]
Sorry for that problem.
We took the BSP from Arduino and I am not sure why the script is not running automatically.

But I am glad it could be solved.
