### ISSUE TITLE
OTAA JOIN FAILED ON RAK4631

### ISSUE THREAD

**Issue by kzmKZuzmo** [RAKWireless/WisBlock#53]
Hello I get this error
I dont now why ?
Is problem on chirpstack or node ? 
![bc8432b805967d82552804397454e6588cd1b789](https://user-images.githubusercontent.com/16986250/166213850-ca00b90c-3b4f-436e-85d2-87408679d1bd.png)

![image](https://user-images.githubusercontent.com/16986250/166214300-92d513dc-7b7f-48f1-9426-547bc6622ff3.png)

uint8_t nodeDeviceEUI[8] = {0x88, 0x88, 0x88, 0x88, 0x88, 0x88, 0x33, 0x33};
uint8_t nodeAppEUI[8] = {0xB8, 0x27, 0xEB, 0xFF, 0xFE, 0x39, 0x00, 0x00};
uint8_t nodeAppKey[16] = {0x88, 0x88, 0x88, 0x88, 0x88, 0x88, 0x88, 0x88, 0x88, 0x88, 0x88, 0x88, 0x88, 0x88, 0x88, 0x88};

**Comment by beegee-tokyo** [comment]
From your screenshot it looks like you setup the Device-Profile in Chirpstack to LoRaWAN MAC version 1.1.
But the library used with RAK4631 is only LoRaMAC version 1.0.2.

Try to change your Device profile:
![image](https://user-images.githubusercontent.com/512690/166221346-85ae839c-01a2-4725-8d09-67a5f7026d8e.png)

**Comment by kzmKZuzmo** [comment]
@beegee-tokyo 
thank you Its work, 
but I have another problem 
13:13:16.129 -> lmh_send fail count 1
13:13:36.121 -> Sending frame now...
13:13:36.121 -> lmh_send fail count 2
13:13:56.129 -> Sending frame now...
13:13:56.161 -> lmh_send ok count 2
13:14:16.146 -> Sending frame now...
13:14:16.146 -> lmh_send fail count 3
13:14:36.147 -> Sending frame now...
13:14:36.147 -> lmh_send fail count 4
13:14:56.142 -> Sending frame now...
13:14:56.142 -> lmh_send ok count 3
13:15:16.139 -> Sending frame now...
13:15:16.139 -> lmh_send fail count 5

Can you help  me with that ?

**Comment by kzmKZuzmo** [comment]
it works thank you

**Comment by beegee-tokyo** [comment]
Is this from the beginning or does it start after a while?

You are on EU868 and there is a duty cycle that defines how often you are allowed to send a packet.
It should be disabled by default, but it still could be the reason.

Can you see packets arriving in Chirpstack?

**Comment by kzmKZuzmo** [comment]
![image](https://user-images.githubusercontent.com/16986250/166234351-f964a969-e82b-4e82-8a35-cdaf65b7c34e.png)
I got this 
where I can find this definition ?

**Comment by beegee-tokyo** [comment]
Do you have defined a Payload Codec in the Device Profile?
You want to forward data to an integration, but it seems there is no decoder defined.
![image](https://user-images.githubusercontent.com/512690/166403028-44394af4-679a-4310-aa60-71e72456db22.png)

**Comment by kzmKZuzmo** [comment]
Yes I did a make a code.
I do not understand why the gateway stops receiving data from the node when the node still sends? I do manualy restart the gateway packet forwarder.
see the difference in times when it was received
![image](https://user-images.githubusercontent.com/16986250/166416258-76c8d8cc-533d-432d-bb7d-843446cf7527.png)

**Comment by beegee-tokyo** [comment]
Do you have the log of the device that stops sending? I have no explanation right now why this would happen.
I have sensor nodes running in my house since months without problems.

What type of gateway are you using? Is the Chirpstack directly running on the gateway or is it a separate unit?

**Comment by danak6jq** [comment]
@kzmKZuzmo perhaps you could share the gateway live reception when the GW stops hearing the RAK4631. See example below of GW live frames; this will show what frames the GW is receiving (and possibly not processing in your CS application) as well as ADR commands send to the mote. Using the 'Download' button, you can get a JSON file of the live frames and attach that here.

I want to check the RSSI/SNR of the uplinks and see if there are ADR commands that possibly command the mote into an unusable state.

<img width="761" alt="image" src="https://user-images.githubusercontent.com/942815/167895187-106ee2e7-6769-4137-92b9-94de99beac7f.png">

**Comment by beegee-tokyo** [comment]
No more feedback. Closed.
