### ISSUE TITLE
Re-Join Network 

### ISSUE THREAD

**Issue by Famosi** [RAKWireless/WisBlock#56]
I'd like to try join the network until a gateway is found.

[Here](https://github.com/beegee-tokyo/SX126x-Arduino/) is described that the `JOINREQ_NBTRIALS` parameter can be used to specify a _"...number to set the number of trials to join the network_".

But how to join the network "for ever". Should I set a very high number? Is there a max value for that parameter? Otherwise, is there a way to set something like: "try join until you join".

Any suggestion?
Thank you

**Comment by beegee-tokyo** [comment]
Better solution (but not well documented)
The LoRaWAN library has two callbacks, one for LoRaWAN join `success` and one for `fail`.
You can restart join from the join failed callback.
These callbacks are used in the [LoRaWan.ino](https://github.com/beegee-tokyo/SX126x-Arduino/blob/master/examples/LoRaWan/LoRaWan.ino) example.

You could restart join from here: [lorawan_join_failed_handler](https://github.com/beegee-tokyo/SX126x-Arduino/blob/dc15fab55f3975171959c2255153d14427d989d4/examples/LoRaWan/LoRaWan.ino#L232)
