### ISSUE TITLE
Gps Tracker example Problem! "check acc"

### ISSUE THREAD

**Issue by danieleberibe** [RAKWireless/WisBlock#59]
Hi I was trying this code and following all the doc I ran into a break in the code the moment before I print the axis data, I am left with "check acc" in the console and it all jams and the console freezes. help me? Thanks in advance

**Comment by beegee-tokyo** [comment]
@danieleberibe 
Can you give a little bit more information? Do you have the log before the crash and can you share it? 

The code works just fine for me here.
![image](https://user-images.githubusercontent.com/512690/179671189-f6553464-f1a9-4d39-b67c-3f093b4793e4.png)

Can the WisBlock connect to a LoRaWAN server?
Does it show **`OTAA Mode, Network Joined!`** in the log?
Is the RAK1904 in the Slot D of the RAK5005-O Base Board?
Is the RAK1910 in the Slot A of the RAK5005-O Base Board?

**Comment by danieleberibe** [comment]
@beegee-tokyo 
Yes, of course then I am using the 2nd gen board and I saw that the 1910 module must be inserted in slot D. If I then insert the 1904 module in A or C the code stops me here (attached image) while if I put it as you have me recommended you don't even join.
![Immagine gps_axis](https://user-images.githubusercontent.com/48356575/179707847-35fcdf2a-e446-4d3d-889b-7bf22f47308c.png)

**Comment by beegee-tokyo** [comment]
As we are discussing this now in Discord, I close it here.
