### ISSUE TITLE
Issue with the region.

### ISSUE THREAD

**Issue by HGarza-Ideas** [RAKWireless/WisBlock#6]
Hi, I just purchase this kit 2 and I want to do the example, but I do not know why always it start as a European model, I bought the American model, I do not where it changes or if RAK gave me a different model.
![Captura](https://user-images.githubusercontent.com/77807078/105406992-c7f70500-5bf2-11eb-9851-7f5be2151803.PNG)

**Comment by beegee-tokyo** [comment]
It is written somewhere in the documentation, but I see we need to make this information easier to find.

You can select the region in Arduino IDE from the Tools menu. You will see an option **Region:**

![image](https://user-images.githubusercontent.com/512690/105437312-cd5c5a00-5c9b-11eb-9e9a-182a5e3a3fa2.png)

If using PlatformIO you set the region in the platformio.ini file of your project as build_flags:
```ini
[env:rak4631]
platform = nordicnrf52
board = wiscore_rak4631
framework = arduino
upload_speed = 115200
build_flags = -DREGION_US915
```
