### ISSUE TITLE
Buffer Modulation

### ISSUE THREAD

**Issue by Devansh-Shah-5400** [RAKWireless/WisBlock#61]
Hey RAK, I was wondering that can I send JSON data or some other type of data to gateway via LoRaWAN OTAA, where I can go:

'temperature': 23 

or 

buffer[i++] = "Temp";   //Which is not possible as it is an unsigned int array
buffer[i++] = 23;

or send it in buffer but I don't want to hardcode it, Thanks for the help!

**Comment by beegee-tokyo** [comment]
Sending data in that way is a waste of payload size.
Better to use Cayenne LPP format. 
There is a library and some examples from [ElectronicCats](https://github.com/ElectronicCats/CayenneLPP).
Most LoRaWAN server have integrated decoders for the Cayenne LPP format and create the JSON string from the binary payload.

I propose as well to ask such questions in our [RAK Forum](https://forum.rakwireless.com/c/wisblock/67), there are many people that can help.
