### ISSUE TITLE
RAK19018 step file does not import

### ISSUE THREAD

**Issue by mkinney** [RAKWireless/WisBlock#62]
The stp file does not seem to be complete for RAK19018. It just errors out when trying to load into Fusion 360.

The file:
https://downloads.rakwireless.com/3D_File/WisBlock/3D_RAK19018.stp

and the last lines:

```
#16079=EDGE_CURVE('NONE',#23243,#23179,#21009,.T.);
#16080=EDGE_CURVE('NONE',#23173,#23566,#20466,.T.);
#160%
```

**Comment by beegee-tokyo** [comment]
Thanks for reporting this.
We will re-upload the file.
In the meantime, can you try the attached one? It loads for me in Fusion360
[RAK19018_VA.zip](https://github.com/RAKWireless/WisBlock/files/10046387/RAK19018_VA.zip)

**Comment by mkinney** [comment]
That works great! Thanks!
