### ISSUE TITLE
Flashing RAK2305 stuck on synchronization process

### ISSUE THREAD

**Issue by hasanabs** [RAKWireless/WisBlock#64]
I have an issue while trying to flash ESP32 WROVER-E (RAK2305 module). When I am flashing my module, it is stuck in the synchronization process. According to the Espressif Flash tools, this issue is because of these problems; 
![Screenshot_20230101_100048](https://user-images.githubusercontent.com/26079804/210182397-5c9e179f-0f18-419a-bbd8-b9c52e0c2004.png)
however, I did follow all the instructions. 

This is my wiring (using FTDI serial). 
![20230101_211851](https://user-images.githubusercontent.com/26079804/210182387-bdc503df-ec6b-48fe-bcef-6c5ca2c31d1e.jpg)

And this is the flashing process that stuck.
![Screenshot_20230101_102147](https://user-images.githubusercontent.com/26079804/210182364-4896ceeb-7327-40f3-84ac-181cbccd280d.png)

Thank you in advanced.

Flasher: https://www.espressif.com/en/support/download/other-tools

**Comment by beegee-tokyo** [comment]
Did you try to lower the baudrate? Try with 115200 baud.

I see two green cables on IO0 and GND, is this the same cable to make sure IO0 is pulled to GND?

**Comment by hasanabs** [comment]
I tried with several baud rate, including 115200.

Yes, right, the same cable is pull-down for IO0.

**Comment by hasanabs** [comment]
It turns out that my USB TTL was not good; thank you for the help.

**Comment by beegee-tokyo** [comment]
Glad you could solve it.

Have fun with WisBlock and let us know if you encounter other problems.
