### ISSUE TITLE
RAK5811 with RAK19001/RAK11310

### ISSUE THREAD

**Issue by SoothingMist** [RAKWireless/WisBlock#80]
The example at https://github.com/RAKWireless/WisBlock/blob/master/examples/RAK11300/IO/RAK5811_0-5V/RAK5811_0-5V.ino is not clear to me on how to read from analog inputs A0 and A1. Have searched, read, and tried as thoroughly as I know how, including forum posts. However, I am unable to tell how to access these two inputs from the programmer's level.

This matter is important to the transition of my GitHub project in LoRaP2P data acquisition and transmission from Arduino/Dragino to RAKwireless. Would appreciate a more-clear example of how to use RAK5811 to access A0 and A1. It is important that I understand this so I can apply it and explain it to others.

**Comment by beegee-tokyo** [comment]
Initialize analog input ==> https://github.com/RAKWireless/WisBlock/blob/bc6d3d5c3edb7c05aeda1a1af98028e50e8f2212/examples/RAK11300/IO/RAK5811_0-5V/RAK5811_0-5V.ino#L38

Read analog input ==> https://github.com/RAKWireless/WisBlock/blob/bc6d3d5c3edb7c05aeda1a1af98028e50e8f2212/examples/RAK11300/IO/RAK5811_0-5V/RAK5811_0-5V.ino#L53

[Quickstart Guide for RAK5811](https://docs.rakwireless.com/product-categories/wisblock/rak5811/quickstart) using A1 of RAK5811

To read from A0 of RAK5811, replace WB_A1 with WB_IO4.

**Comment by SoothingMist** [comment]
Thank you for your feedback Bernd. It is much appreciated, as is your patience.

Something I have not communicated well is that I am trying to read from analog inputs A0 and A1 within the same program, such that A0 and A1 are independent and connected to completely different sensors.

Working with the code at https://raw.githubusercontent.com/RAKWireless/WisBlock/bc6d3d5c3edb7c05aeda1a1af98028e50e8f2212/examples/RAK11300/IO/RAK5811_0-5V/RAK5811_0-5V.ino, I noticed that WB_A1 is hardwired in one place and used via ADC0 in another. I began by replacing ADC0 with WB_A1. Then I changed WB_A1 to WB_IO4. The result is attached. Injecting a 0-5vdc at A0 did not show variations in the WB_IO4 case. The original arrangement with WB_A1 did show variation for A1.

[RAK5811-NewTest_2.ino.txt](https://github.com/user-attachments/files/17924985/RAK5811-NewTest_2.ino.txt)


Two questions:

(1) Should the input variable at line 52, adc_select_input(1), should be changed to 0 if A0 is receiving input?

(2) Is it possible to arrange the code so that A0 and A1 can be read? Or, would it be necessary to repeat the setup step prior to reading from different analog inputs?

Many thanks for your discussion on this matter.

**Comment by beegee-tokyo** [comment]
Please check attached example. I changed it to read from both A0 and A1 of the RAK5811.

Test setup:
![image](https://github.com/user-attachments/assets/e2aaa828-de0d-4a97-b5cb-70a57ab1b592)

USB log output:
![image](https://github.com/user-attachments/assets/fec5d075-6f19-4853-9cde-5019cb2ad2f4)

Code:
[RAK5811_0-5V.zip](https://github.com/user-attachments/files/17928070/RAK5811_0-5V.zip)

**Comment by SoothingMist** [comment]
Wow !!!  This is great. Many thanks. Attached is the first rough draft of what is going into the documentation of the overall project. Had good experiences with this new code. Have a happy thanksgiving.
[Using_RAK5811.pdf](https://github.com/user-attachments/files/17952204/Using_RAK5811.pdf)

**Comment by beegee-tokyo** [comment]
Glad it works for you.
will close this issue now.
