### ISSUE TITLE
Reset

### ISSUE THREAD

**Issue by HGarza-Ideas** [RAKWireless/WisBlock#9]
Hi, I have a issue, when I try to start this example, I always have to push the button reset. And i would like that i don't need to push that button to start working. Because it is going to be an autonomous GPS.
Thank you.

**Comment by beegee-tokyo** [comment]
Is your WisBlock from the Beta-Starter kit?

The first pre-sale RAK4631 have a problem with the bootloader when using the GPS module.

You need to update the bootloader. We have a tutorial for the [bootloader update](https://github.com/RAKWireless/WisBlock/tree/master/bootloader) with the Segger JLink.

Or, if you have a DAPLink device or our RAKDAP1, you can follow this tutorial about [RAKDAP1](https://docs.rakwireless.com/Product-Categories/Accessories/RAKDAP1-Flash-and-Debug-Tool/Quickstart/#installation). When using DAPLink or RAKDAP1, the command to flash the bootloader is    
```
pyocd flash -t nrf52840 RAK4630_bootloader.hex
```     
The Bootloader hex file is in the [Bootloader section](https://github.com/RAKWireless/WisBlock/tree/master/bootloader) of this repo.

Updating the bootloader from ArduinoIDE is not supported.

**Comment by HGarza-Ideas** [comment]
They don't tell if my rak4631 is a beta-started kit, but it doesn't matter if I am using the GPS module or not, always when I connect the wis-block to my computer it doesn't recognize the dispositive, I always have to press the reset button for my computer to detect it.

**Comment by beegee-tokyo** [comment]
That seems to be a different problem.
Does the WisBlock start when you connect the USB cable to a charger or supply it from a battery?
Did you try different USB ports?
Did yu try different USB cables?
Can you try on a different computer?

**Comment by HGarza-Ideas** [comment]
I used another USB cable and another USB port, also I tried with another computer. I connected a charger and also I have the same problem.

**Comment by beegee-tokyo** [comment]
But is your application on the RAK4631 starting?
For example, if you flash a simple LED blink application, does the software start and the LED's blink?

**Comment by HGarza-Ideas** [comment]
No, I have to push the reset button.

But if I wait 5 minutes the program start, but I don't want to wait 5 minutes.

https://user-images.githubusercontent.com/77807078/110497059-bba00c00-80bb-11eb-9b62-c7067ea82eb8.mp4

**Comment by beegee-tokyo** [comment]
In the video you still have the GPS module connected.
![image](https://user-images.githubusercontent.com/512690/110572498-7ef41380-8194-11eb-9c13-f536613df34f.png)

Please try **WITHOUT** the GPS module.

I have 5 WisBlock systems running here, none of them has this problem. I am not sure what your problem is.

**Comment by HGarza-Ideas** [comment]
Without the GPS module it start immediately. But the problem is that the application that I want to do (GPS tracker) use the GPS module.

**Comment by beegee-tokyo** [comment]
In this case I am proposing you follow my [first answer here](https://github.com/RAKWireless/WisBlock/issues/9#issuecomment-791214496} and flash the latest bootloader.
